### PR TITLE
Milestone 3: TIC-tac-toc  - Game logic

### PR DESCRIPTION
**Pull request by hillarioh**
Hi,
This is the third milestone of the ruby course and it entailed building using oop to come up with the game. We have used four classes i.e Main, game, player and board classes. All the puts and gets are in the main.rb as stipulated in the requirements part. This is our submission for review and hope for the best.

### CODE REVIEW

**Review by Forison — CHANGES_REQUESTED** [review]
## Status:: Require changes❌
# 👋 team,
Hi you have done a good job so far, your classes are well separated and you have implemented quite a number of concepts in Ruby's OOP concept.
Here is what we have to do to get this project approved.
* [ ] Make sure you resolve the conflict on your branch before you submit the project for review. This making the review challenging.
 ## After you have resolved the issue above ensure the following requirements are met.
* [ ] No `puts/print` and `get.chomp` outside `main.rb` file. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/only_main_print.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
* [ ] The application does not allow a player to move into an occupied position
* [ ] The application does not exit due to invalid input - it informs the player about it and asks for their move again
* [ ] The application saves players' move and displays the status of the board after that.
* [ ] The application can determine if a move is a winning move
  * [ ] The application can detect a sequence of three horizontal elements that are equal
  * [ ] The application can detect a sequence of three vertical elements that are equal
  * [ ] The application can detect a sequence of three equal elements in a diagonal from left and right to right
* [ ] The application can tell if there was a draw after players move
* [ ] The application can change active player

> _note: It is good practice to have your commit statements in the present tense. ie add instead of added

## That is it, kindly make these changes and submit the project for review🚀.
#### Happy coding💻
Addo

**Comment by hillarioh** [comment]
Hello, The linter check passes on my local machine, you can have a look too  for comparison .

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great progress @team :clap: :clap: However, some requirements need to be implemented in order to get approval for this milestone. Check :arrow_down: 

- **[REQUIRED]** All classes are kept in `lib` directory. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone1/lib_dir_exist.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
  - The **Main** class was never instantiated in the project, it's unnecessary to make it a class.
  - I recommend either make it a module **OR** make the methods global and change the **Game** class so it delegates handling the flow of the game (i.e UI interactions) to **main.rb**
  
- **[MILESTONE 2]** The game loop should remain in main.rb and should handle UI interactions for each player separately(DRY loop)

##### behavior
image
  

* [ ] The application does not allow a player to move into an occupied position
* [ ] The application does not exit due to invalid input - it informs player about it and asks for their move again
* [ ] The application saves players move and displays status of board after that.
  - The game breaks when I choose an occupied position
  - The game stores the invalid name even though it's asking to enter a valid name.

### That's it :relaxed: When finished, kindly submit a code re-review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

**Comment by hillarioh** [comment]
Hello, The linter check passes on my local machine, you can have a look too for comparison .

**Review by euqueme — CHANGES_REQUESTED** [review]
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @hillarioh and @Calvinoea :handshake: 

### Thank you for doing all the changes requested by the previous reviewers, :medal_sports: :medal_sports: I have to give you some claps for having a readme file in this milestone, the next would be very easy for you :clap: :clap: :clap: there's only one change to make :point_down: 

#### General

* [ ] Linters config: Do not make any changes in config files - they represent style guidelines that you share with your team - which is a group of all Microverse students. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/))

- I see you've changed your .rubocop.yml file, so maybe that's why you are having problems with stickler please use the [original](https://github.com/microverseinc/linters-config/blob/master/ruby/.rubocop.yml) and if you need to disable some rules do it with comments within your code [here](https://stackoverflow.com/questions/26342570/rubocop-linelength-how-to-ignore-lines-with-comments) you can find some examples on how to do so.

### That's it, team! :raised_hands: 

### Please :pray: do the changes :man_technologist: :man_technologist: and submit back for a code review when you are done :memo: 

Happy Coding :rocket: 

Any questions? please ask me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :vertical_traffic_light:

**Comment by hillarioh** [comment]
Hello, The linter check passes on my local machine, you can have a look too for comparison, it occured due merge conflict with the development branch after trying to solve it.

**Comment by hillarioh** [comment]
Linter is working fine after making changes to the base branch

**Comment by Anna-Myzukina** [comment]
## Hi team ! Very nice project! :wave: 

# You did a great job, approved  :+1:

* NOTE Ruby methods automatically returns the last evaluated statement therefore, there is no need for explicit declaration `return`

### Go and merge to dev.
`Goodluck in your last milestone Happy coding ` <g-emoji class="g-emoji" alias="computer" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4bb.png">computer</g-emoji>

**Pull request merged**
